import { 
  Assurance, 
  Partenaire, 
  ArticleStock, 
  Fournisseur, 
  DossierSinistre, 
  Facture, 
  BonSortie,
  BonLivraison,
  ReglementRecette,
  BonCommandeFournisseur,
  DevisClient
} from '@/types';

export const GARAGE_INFO = {
  nom: 'GLOBAL PARE-BRISE',
  formeJuridique: 'SARL',
  adresse: 'LA FERAIL HAY ALKARAM N 179 MARRAKECH - MAROC',
  telephone: '0700367182 / 0524307501',
  email: 'globalazurmaroc@gmail.com',
  siteWeb: 'www.globalparebrise.ma',
  ice: '003011381000053',
  patente: '64008343',
  ifiscal: '51763123',
  rc: '49821 Marrakech',
  cnss: '8923412',
  rib: '011 780 0000 123456789012 34 (Attijariwafa Bank)',
};

export const INITIAL_ASSURANCES: Assurance[] = [
  {
    id: 'ass-1',
    nom: 'Wafa Assurance',
    code: 'WAFA',
    telephone: '05 22 54 55 56',
    email: 'sinistres.auto@wafaassurance.co.ma',
    adresse: '1 Boulevard Abdelmoumen, Casablanca',
    delaiReglementMoyenJours: 45,
  },
  {
    id: 'ass-2',
    nom: 'RMA (Royale Marocaine d\'Assurance)',
    code: 'RMA',
    telephone: '05 22 20 40 40',
    email: 'reglements.auto@rma.co.ma',
    adresse: '83 Avenue de l\'Armée Royale, Casablanca',
    delaiReglementMoyenJours: 35,
  },
  {
    id: 'ass-3',
    nom: 'Sanlam Maroc',
    code: 'SANLAM',
    telephone: '05 22 42 06 06',
    email: 'gestion.sinistre@sanlam.ma',
    adresse: '216 Boulevard Zerktouni, Casablanca',
    delaiReglementMoyenJours: 40,
  },
  {
    id: 'ass-4',
    nom: 'AXA Assurance Maroc',
    code: 'AXA',
    telephone: '05 22 88 92 92',
    email: 'priseencharge@axa.ma',
    adresse: '120-122 Avenue Hassan II, Casablanca',
    delaiReglementMoyenJours: 30,
  },
  {
    id: 'ass-5',
    nom: 'AtlantaSanad',
    code: 'ATLANTASANAD',
    telephone: '05 22 95 78 00',
    email: 'sinistre.auto@atlantasanad.ma',
    adresse: '181 Boulevard d\'Anfa, Casablanca',
    delaiReglementMoyenJours: 50,
  },
  {
    id: 'ass-6',
    nom: 'MAMDA - MCMA',
    code: 'MAMDA',
    telephone: '05 37 68 80 00',
    email: 'contact@mamda-mcma.ma',
    adresse: 'Place Moulay Hassan, Rabat',
    delaiReglementMoyenJours: 40,
  },
];

export const INITIAL_PARTENAIRES: Partenaire[] = [
  {
    id: 'part-1',
    nom: 'Cabinet d\'Assurance Al Baraka (Courtier)',
    type: 'COURTIER',
    telephone: '05 22 30 11 22',
    ville: 'Casablanca',
    tauxCommissionPourcent: 8,
  },
  {
    id: 'part-2',
    nom: 'Carrosserie Auto Moderne Ain Sebaa',
    type: 'CARROSSIER',
    telephone: '06 61 40 50 60',
    ville: 'Casablanca',
    tauxCommissionPourcent: 5,
  },
  {
    id: 'part-3',
    nom: 'Dépannage Express & Assistance 24/7',
    type: 'DEPANNEUR',
    telephone: '06 63 99 88 77',
    ville: 'Mohammedia',
    tauxCommissionPourcent: 5,
  },
  {
    id: 'part-4',
    nom: 'Atlas Location Voitures Longue Durée',
    type: 'AGENCE_LOCATION',
    telephone: '05 22 80 90 00',
    ville: 'Casablanca',
    tauxCommissionPourcent: 10,
  },
];

export const INITIAL_FOURNISSEURS: Fournisseur[] = [
  {
    id: 'fourn-1',
    nom: 'Saint-Gobain Sekurit Maroc',
    ice: '001569483000078',
    telephone: '05 22 66 12 00',
    email: 'commandes@saint-gobain-sekurit.ma',
    ville: 'Casablanca',
    specialite: 'Vitrages d\'origine première monte',
  },
  {
    id: 'fourn-2',
    nom: 'Pilkington Vitrage Auto Distribution',
    ice: '002019485000032',
    telephone: '05 22 34 56 78',
    email: 'contact@pilkington-maroc.ma',
    ville: 'Tanger',
    specialite: 'Pare-brise et capteurs de pluie',
  },
  {
    id: 'fourn-3',
    nom: 'Sika Maroc (Chimie & Adhésifs)',
    ice: '000045812000099',
    telephone: '05 22 35 41 41',
    email: 'info@ma.sika.com',
    ville: 'Bouskoura',
    specialite: 'Colle polyuréthane pare-brise & Primaires',
  },
];

export const INITIAL_STOCK: ArticleStock[] = [
  {
    id: 'art-1',
    reference: 'PB-DAC-LOG2',
    codeEurocode: '7288AGS',
    designation: 'Pare-Brise Teinté Vert - Dacia Logan II / Sandero II',
    type: 'PARE_BRISE',
    quantiteEnStock: 12,
    stockMinimumAlerte: 4,
    prixAchatHT: 650,
    prixVenteHT: 1200,
    emplacement: 'Allée A - Rack 01',
  },
  {
    id: 'art-2',
    reference: 'PB-REN-CLIO5',
    codeEurocode: '7295AGS',
    designation: 'Pare-Brise avec Capteur Pluie - Renault Clio V',
    type: 'PARE_BRISE',
    quantiteEnStock: 7,
    stockMinimumAlerte: 3,
    prixAchatHT: 950,
    prixVenteHT: 1750,
    emplacement: 'Allée A - Rack 03',
  },
  {
    id: 'art-3',
    reference: 'PB-VW-GOLF7',
    codeEurocode: '8589AGS',
    designation: 'Pare-Brise Acoustique & Caméra ADAS - VW Golf VII / VIII',
    type: 'PARE_BRISE',
    quantiteEnStock: 4,
    stockMinimumAlerte: 2,
    prixAchatHT: 1400,
    prixVenteHT: 2600,
    emplacement: 'Allée B - Rack 02',
  },
  {
    id: 'art-4',
    reference: 'PB-PEUG-208',
    codeEurocode: '6565AGS',
    designation: 'Pare-Brise Teinté Capteur - Peugeot 208 II / 2008',
    type: 'PARE_BRISE',
    quantiteEnStock: 6,
    stockMinimumAlerte: 3,
    prixAchatHT: 880,
    prixVenteHT: 1650,
    emplacement: 'Allée B - Rack 04',
  },
  {
    id: 'art-5',
    reference: 'PB-HYU-TUCSON',
    codeEurocode: '4160AGS',
    designation: 'Pare-Brise Dégivrant & Caméra - Hyundai Tucson IV',
    type: 'PARE_BRISE',
    quantiteEnStock: 2,
    stockMinimumAlerte: 2,
    prixAchatHT: 1650,
    prixVenteHT: 3100,
    emplacement: 'Allée C - Rack 01',
  },
  {
    id: 'art-6',
    reference: 'COLLE-SIKA-DRIVE',
    codeEurocode: 'SIKA-300ML',
    designation: 'Cartouche Mastic Polyuréthane SikaTack Drive (300ml)',
    type: 'COLLE',
    quantiteEnStock: 28,
    stockMinimumAlerte: 15,
    prixAchatHT: 85,
    prixVenteHT: 180,
    emplacement: 'Armoire Consommables C1',
  },
  {
    id: 'art-7',
    reference: 'PRIM-SIKA-ACTIVE',
    codeEurocode: 'SIKA-PRIM',
    designation: 'Primaire d\'adhérence universel Sika Aktivator-100',
    type: 'COLLE',
    quantiteEnStock: 8,
    stockMinimumAlerte: 5,
    prixAchatHT: 65,
    prixVenteHT: 120,
    emplacement: 'Armoire Consommables C1',
  },
  {
    id: 'art-8',
    reference: 'LUN-MERC-C220',
    codeEurocode: '5441BGSE',
    designation: 'Lunette Arrière Dégivrante - Mercedes Classe C W205',
    type: 'LUNETTE_AR',
    quantiteEnStock: 3,
    stockMinimumAlerte: 2,
    prixAchatHT: 1300,
    prixVenteHT: 2400,
    emplacement: 'Allée D - Rack 01',
  },
  {
    id: 'art-9',
    reference: 'VIT-AVD-DAC-DUST',
    codeEurocode: '7285FDG',
    designation: 'Vitre Latérale Avant Droite - Dacia Duster II',
    type: 'VITRE_LATERALE',
    quantiteEnStock: 5,
    stockMinimumAlerte: 2,
    prixAchatHT: 320,
    prixVenteHT: 650,
    emplacement: 'Allée D - Rack 03',
  },
];

export const INITIAL_DOSSIERS: DossierSinistre[] = [
  {
    id: 'dos-1',
    numeroDossier: 'DOS-2026-0042',
    typeDossier: 'ASSURANCE',
    dateCreation: '2026-10-02',
    client: {
      id: 'cli-1',
      nom: 'Youssef El Amrani',
      telephone: '06 61 12 34 56',
      email: 'y.elamrani@gmail.com',
      cin: 'BK654321',
      ville: 'Marrakech',
    },
    vehicule: {
      id: 'veh-1',
      clientId: 'cli-1',
      immatriculation: '45892 | A | 6',
      marque: 'Dacia',
      modele: 'Logan II 1.5 dCi',
      annee: 2020,
      chassisVin: 'VF14SD90264819203',
      kilometrage: 84500,
    },
    assurance: INITIAL_ASSURANCES[0], // Wafa
    partenaire: INITIAL_PARTENAIRES[0], // Al Baraka
    numeroSinistre: 'SIN-WAFA-2026/8941',
    numeroPolice: 'POL-9923847-01',
    dateSinistre: '2026-09-28',
    montantTotalTTC: 1800,
    montantPriseEnChargeAssurance: 1800,
    montantFranchise: 250,
    franchisePayeeParClient: false,
    franchiseOfferte: true, // Offerte en cadeau promo
    statut: 'DEPOSE_ASSURANCE',
    dateDepotAssurance: '2026-10-04',
    photos: {
      avantSinistreUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=600&q=80',
      apresPoseUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80',
      carteGriseUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80',
    },
    documents: [
      {
        id: 'doc-1',
        nom: 'Accord_Prise_En_Charge_Wafa_8941.pdf',
        typeDocument: 'PRISE_EN_CHARGE_ASSURANCE',
        url: '#',
        taille: '420 Ko',
        dateAjout: '2026-10-02',
      },
      {
        id: 'doc-2',
        nom: 'Rapport_Expertise_BrisDeGlace.pdf',
        typeDocument: 'RAPPORT_EXPERTISE',
        url: '#',
        taille: '1.2 Mo',
        dateAjout: '2026-10-03',
      },
    ],
    bonSortieId: 'bs-1',
    bonLivraisonId: 'bl-1',
    factureAssuranceId: 'fac-1',
    poseur: 'Karim Bennani (Chef d\'atelier)',
    observations: 'Impact suite à projection de caillou sur l\'autoroute. Pose validée.',
  },
  {
    id: 'dos-2',
    numeroDossier: 'DOS-2026-0043',
    typeDossier: 'ASSURANCE',
    dateCreation: '2026-10-03',
    client: {
      id: 'cli-2',
      nom: 'Fatima Zahra Benkirane',
      telephone: '06 63 98 76 54',
      email: 'fz.benkirane@hotmail.com',
      cin: 'A498210',
      ville: 'El Jadida',
    },
    vehicule: {
      id: 'veh-2',
      clientId: 'cli-2',
      immatriculation: '11204 | B | 1',
      marque: 'Renault',
      modele: 'Clio V Intens',
      annee: 2022,
      chassisVin: 'VF1RJA00569812450',
      kilometrage: 42100,
    },
    assurance: INITIAL_ASSURANCES[1], // RMA
    numeroSinistre: 'SIN-RMA-2026-04192',
    numeroPolice: 'POL-RMA-774411',
    dateSinistre: '2026-10-01',
    montantTotalTTC: 2450,
    montantPriseEnChargeAssurance: 2200,
    montantFranchise: 250,
    franchisePayeeParClient: true,
    franchiseOfferte: false,
    statut: 'VALIDE_REGLE',
    dateDepotAssurance: '2026-10-03',
    dateReglementAssurance: '2026-10-06',
    photos: {
      avantSinistreUrl: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=600&q=80',
      apresPoseUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=600&q=80',
      carteGriseUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80',
    },
    bonSortieId: 'bs-2',
    factureAssuranceId: 'fac-2',
    poseur: 'Rachid Mansouri',
    observations: 'Capteur de pluie réinitialisé et testé avec succès.',
  },
  {
    id: 'dos-3',
    numeroDossier: 'DOS-2026-0044',
    typeDossier: 'ASSURANCE',
    dateCreation: '2026-10-05',
    client: {
      id: 'cli-3',
      nom: 'Société MaroTrans Express',
      telephone: '05 22 70 80 90',
      cin: 'ICE: 001928374000012',
      ville: 'Marrakech',
    },
    vehicule: {
      id: 'veh-3',
      clientId: 'cli-3',
      immatriculation: '87642 | D | 6',
      marque: 'Volkswagen',
      modele: 'Golf VII GTD',
      annee: 2021,
      chassisVin: 'WVWZZZAUZMP098124',
      kilometrage: 110000,
    },
    assurance: INITIAL_ASSURANCES[2], // Sanlam
    partenaire: INITIAL_PARTENAIRES[1], // Carrosserie Moderne
    numeroSinistre: 'SIN-SANLAM-77218',
    numeroPolice: 'SAN-AUTO-40912',
    dateSinistre: '2026-10-04',
    montantTotalTTC: 3500,
    montantPriseEnChargeAssurance: 3500,
    montantFranchise: 0,
    franchisePayeeParClient: false,
    franchiseOfferte: false,
    statut: 'EN_COURS_POSE',
    photos: {
      avantSinistreUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=600&q=80',
      carteGriseUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80',
    },
    bonSortieId: 'bs-3',
    poseur: 'Karim Bennani',
    observations: 'Calibrage de la caméra de franchissement de ligne prévu après polymérisation de la colle.',
  },
  {
    id: 'dos-4',
    numeroDossier: 'DOS-2026-0045',
    typeDossier: 'ASSURANCE',
    dateCreation: '2026-10-06',
    client: {
      id: 'cli-4',
      nom: 'Mehdi Chraibi',
      telephone: '06 70 45 12 89',
      email: 'm.chraibi@menara.ma',
      cin: 'C789456',
      ville: 'El Jadida',
    },
    vehicule: {
      id: 'veh-4',
      clientId: 'cli-4',
      immatriculation: '23981 | A | 6',
      marque: 'Peugeot',
      modele: '208 Allure',
      annee: 2023,
      chassisVin: 'VR3UPHN0099882211',
      kilometrage: 28000,
    },
    assurance: INITIAL_ASSURANCES[3], // AXA
    numeroSinistre: 'SIN-AXA-2026/0991',
    numeroPolice: 'AXA-MAROC-330192',
    dateSinistre: '2026-10-05',
    montantTotalTTC: 2200,
    montantPriseEnChargeAssurance: 2200,
    montantFranchise: 200,
    franchisePayeeParClient: false,
    franchiseOfferte: true,
    statut: 'NOUVEAU',
    photos: {},
    poseur: 'En attente d\'affectation',
    observations: 'Client reçu ce matin. Prise en charge AXA accordée par fax/email.',
  },
  {
    id: 'dos-5',
    numeroDossier: 'DOS-2026-0046',
    typeDossier: 'PARTICULIER_COMPTANT',
    dateCreation: '2026-10-06',
    client: {
      id: 'cli-5',
      nom: 'Abderrahim Zniber',
      telephone: '06 61 77 88 99',
      cin: 'EE459201',
      ville: 'Marrakech',
    },
    vehicule: {
      id: 'veh-5',
      clientId: 'cli-5',
      immatriculation: '55190 | A | 26',
      marque: 'Dacia',
      modele: 'Sandero Stepway',
      annee: 2021,
      chassisVin: 'UU15SD00889911223',
      kilometrage: 62000,
    },
    // Sans assurance : pas de police ni sinistre
    montantTotalTTC: 1450,
    montantPriseEnChargeAssurance: 0,
    montantFranchise: 0,
    franchisePayeeParClient: false,
    franchiseOfferte: false,
    statut: 'VALIDE_REGLE',
    photos: {
      avantSinistreUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=600&q=80',
      apresPoseUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80',
    },
    poseur: 'Karim Bennani (Chef d\'atelier)',
    observations: 'Client particulier sans garantie bris de glace. Règlement intégral effectué au comptoir atelier.',
  },
];

export const INITIAL_BONS_SORTIE: BonSortie[] = [
  {
    id: 'bs-1',
    numeroBS: 'BS-2026-0042',
    dossierId: 'dos-1',
    dateSortie: '2026-10-02',
    poseur: 'Karim Bennani',
    lignes: [
      {
        articleId: 'art-1',
        reference: 'PB-DAC-LOG2',
        designation: 'Pare-Brise Teinté Vert - Dacia Logan II / Sandero II (7288AGS)',
        quantite: 1,
      },
      {
        articleId: 'art-6',
        reference: 'COLLE-SIKA-DRIVE',
        designation: 'Cartouche Mastic Polyuréthane SikaTack Drive (300ml)',
        quantite: 1,
      },
    ],
    notes: 'Sortie pour atelier principal - Dacia Logan 45892-A-6',
  },
  {
    id: 'bs-2',
    numeroBS: 'BS-2026-0043',
    dossierId: 'dos-2',
    dateSortie: '2026-10-03',
    poseur: 'Rachid Mansouri',
    lignes: [
      {
        articleId: 'art-2',
        reference: 'PB-REN-CLIO5',
        designation: 'Pare-Brise avec Capteur Pluie - Renault Clio V (7295AGS)',
        quantite: 1,
      },
      {
        articleId: 'art-6',
        reference: 'COLLE-SIKA-DRIVE',
        designation: 'Cartouche Mastic Polyuréthane SikaTack Drive (300ml)',
        quantite: 1,
      },
      {
        articleId: 'art-7',
        reference: 'PRIM-SIKA-ACTIVE',
        designation: 'Primaire d\'adhérence universel Sika Aktivator-100',
        quantite: 1,
      },
    ],
    notes: 'Sortie atelier - Renault Clio 11204-B-1',
  },
  {
    id: 'bs-3',
    numeroBS: 'BS-2026-0044',
    dossierId: 'dos-3',
    dateSortie: '2026-10-05',
    poseur: 'Karim Bennani',
    lignes: [
      {
        articleId: 'art-3',
        reference: 'PB-VW-GOLF7',
        designation: 'Pare-Brise Acoustique & Caméra ADAS - VW Golf VII / VIII (8589AGS)',
        quantite: 1,
      },
      {
        articleId: 'art-6',
        reference: 'COLLE-SIKA-DRIVE',
        designation: 'Cartouche Mastic Polyuréthane SikaTack Drive (300ml)',
        quantite: 2,
      },
    ],
    notes: 'Sortie pour remplacement pare-brise Golf 7 - 87642-D-6',
  },
];

export const INITIAL_FACTURES: Facture[] = [
  {
    id: 'fac-1',
    numeroFacture: 'FA-2026-0089',
    dossierId: 'dos-1',
    destinataire: 'ASSURANCE',
    dateEmission: '2026-10-04',
    dateEcheance: '2026-11-18',
    lignes: [
      {
        designation: 'Fourniture Pare-Brise Teinté Dacia Logan II (Eurocode 7288AGS)',
        codeEurocode: '7288AGS',
        quantite: 1,
        prixUnitaireHT: 1200,
        tauxTva: 20,
        totalHT: 1200,
      },
      {
        designation: 'Colle pare-brise haute adhérence & Primaire Sika',
        quantite: 1,
        prixUnitaireHT: 180,
        tauxTva: 20,
        totalHT: 180,
      },
      {
        designation: 'Main d\'œuvre pose et dépose pare-brise collé',
        quantite: 1,
        prixUnitaireHT: 120,
        tauxTva: 20,
        totalHT: 120,
      },
    ],
    totalHT: 1500,
    totalTVA: 300,
    totalTTC: 1800,
    montantRegle: 0,
    statutPaiement: 'EN_ATTENTE',
  },
  {
    id: 'fac-2',
    numeroFacture: 'FA-2026-0090',
    dossierId: 'dos-2',
    destinataire: 'ASSURANCE',
    dateEmission: '2026-10-03',
    dateEcheance: '2026-11-03',
    lignes: [
      {
        designation: 'Fourniture Pare-Brise Capteur Renault Clio V (Eurocode 7295AGS)',
        codeEurocode: '7295AGS',
        quantite: 1,
        prixUnitaireHT: 1550,
        tauxTva: 20,
        totalHT: 1550,
      },
      {
        designation: 'Kit colle polyuréthane & polymérisation rapide',
        quantite: 1,
        prixUnitaireHT: 180,
        tauxTva: 20,
        totalHT: 180,
      },
      {
        designation: 'Main d\'œuvre pose et calibrage capteur pluie',
        quantite: 1,
        prixUnitaireHT: 103.33,
        tauxTva: 20,
        totalHT: 103.33,
      },
    ],
    totalHT: 1833.33,
    totalTVA: 366.67,
    totalTTC: 2200,
    montantRegle: 2200,
    statutPaiement: 'REGLE',
    datePaiement: '2026-10-06',
    referencePaiement: 'Virement RMA N° 092813',
  },
];

export const INITIAL_BONS_LIVRAISON: BonLivraison[] = [
  {
    id: 'bl-1',
    numeroBL: 'BL-2026-0042',
    dossierId: 'dos-1',
    dateLivraison: '2026-10-02',
    livreurPoseur: 'Karim Bennani (Chef d\'atelier)',
    receptionnaireNom: 'Youssef El Amrani',
    receptionnaireCin: 'BK654321',
    lignes: [
      {
        designation: 'Pare-Brise Teinté Vert - Dacia Logan II / Sandero II (Conforme)',
        codeEurocode: '7288AGS',
        quantite: 1,
      },
      {
        designation: 'Colle polyuréthane haute performance & séchage rapide',
        codeEurocode: 'SIKA-300ML',
        quantite: 1,
      },
    ],
    observations: 'Véhicule réceptionné par le client en parfait état de propreté et étanchéité testée.',
  },
  {
    id: 'bl-2',
    numeroBL: 'BL-2026-0043',
    dossierId: 'dos-2',
    dateLivraison: '2026-10-03',
    livreurPoseur: 'Rachid Mansouri',
    receptionnaireNom: 'Fatima Zahra Benkirane',
    receptionnaireCin: 'A498210',
    lignes: [
      {
        designation: 'Pare-Brise avec Capteur Pluie - Renault Clio V',
        codeEurocode: '7295AGS',
        quantite: 1,
      },
      {
        designation: 'Kit collage & calage capteur pluie',
        quantite: 1,
      },
    ],
    observations: 'Pose effectuée avec succès. Détecteur de pluie opérationnel.',
  },
];

export const INITIAL_RECETTES: ReglementRecette[] = [
  {
    id: 'rec-1',
    numeroRecu: 'REC-2026-0089',
    dossierId: 'dos-2',
    factureId: 'fac-2',
    payeurNom: 'RMA (Royale Marocaine d\'Assurance)',
    sourceType: 'ASSURANCE',
    modePaiement: 'VIREMENT',
    montant: 2200,
    datePaiement: '2026-10-06',
    referenceDocument: 'VIR-RMA-092813',
    banque: 'Attijariwafa Bank',
    statut: 'ENCAISSE',
    dateEncaissementEffectif: '2026-10-06',
    notes: 'Règlement prise en charge dossier N° SIN-RMA-2026-04192',
  },
  {
    id: 'rec-2',
    numeroRecu: 'REC-2026-0090',
    dossierId: 'dos-2',
    payeurNom: 'Fatima Zahra Benkirane (Client)',
    sourceType: 'CLIENT',
    modePaiement: 'ESPECES',
    montant: 250,
    datePaiement: '2026-10-03',
    referenceDocument: 'ESP-ATELIER-102',
    statut: 'ENCAISSE',
    dateEncaissementEffectif: '2026-10-03',
    notes: 'Règlement franchise bris de glace à l\'accueil',
  },
  {
    id: 'rec-3',
    numeroRecu: 'REC-2026-0091',
    dossierId: 'dos-3',
    payeurNom: 'Société MaroTrans Express',
    sourceType: 'CLIENT',
    modePaiement: 'CHEQUE',
    montant: 3500,
    datePaiement: '2026-10-05',
    dateEcheance: '2026-10-25',
    referenceDocument: 'CHQ N° 7894512',
    banque: 'Banque Populaire (BCP)',
    statut: 'EN_ATTENTE_ECHEANCE',
    notes: 'Chèque de garantie en attente de validation accord expert Sanlam',
  },
  {
    id: 'rec-4',
    numeroRecu: 'REC-2026-0092',
    payeurNom: 'Carrosserie Auto Moderne (Partenaire)',
    sourceType: 'PARTENAIRE',
    modePaiement: 'EFFET',
    montant: 5800,
    datePaiement: '2026-09-28',
    dateEcheance: '2026-11-15',
    referenceDocument: 'TRAITE-LCR-44102',
    banque: 'BMCE Bank of Africa',
    statut: 'EN_ATTENTE_ECHEANCE',
    notes: 'Effet de commerce 45 jours fin de mois pour lot vitrage posé',
  },
  {
    id: 'rec-5',
    numeroRecu: 'REC-2026-0093',
    dossierId: 'dos-4',
    payeurNom: 'Mehdi Chraibi',
    sourceType: 'CLIENT',
    modePaiement: 'ESPECES',
    montant: 200,
    datePaiement: '2026-10-06',
    referenceDocument: 'ESP-ATELIER-105',
    statut: 'ENCAISSE',
    dateEncaissementEffectif: '2026-10-06',
    notes: 'Acompte réservation pare-brise Peugeot 208',
  },
];

export const INITIAL_COMMANDES_FOURNISSEURS: BonCommandeFournisseur[] = [
  {
    id: 'bc-1',
    numeroBC: 'BC-2026-0012',
    fournisseurId: 'fourn-1', // Saint-Gobain Sekurit
    dateCommande: '2026-09-28',
    dateLivraisonPrevue: '2026-10-02',
    dateReceptionReelle: '2026-10-02',
    agenceVille: 'Marrakech',
    lignes: [
      {
        id: 'lbc-1',
        articleId: 'art-1',
        designation: 'Pare-Brise Teinté Vert - Dacia Logan II / Sandero II (7288AGS)',
        reference: 'PB-DAC-LOG2',
        codeEurocode: '7288AGS',
        quantite: 10,
        prixUnitaireAchatHT: 650,
        totalHT: 6500,
      },
      {
        id: 'lbc-2',
        articleId: 'art-2',
        designation: 'Pare-Brise avec Capteur Pluie - Renault Clio V (7295AGS)',
        reference: 'PB-REN-CLIO5',
        codeEurocode: '7295AGS',
        quantite: 5,
        prixUnitaireAchatHT: 950,
        totalHT: 4750,
      },
    ],
    totalHT: 11250,
    tauxTva: 20,
    totalTVA: 2250,
    totalTTC: 13500,
    statutCommande: 'RECUE_CONFORME',
    statutPaiement: 'PAYE_TOTAL',
    montantPaye: 13500,
    modePaiement: 'VIREMENT',
    referencePaiement: 'VIR-SG-2026-0982',
    datePaiementEffectif: '2026-10-03',
    numeroBLFournisseur: 'BL-SG-99412',
    numeroFactureFournisseur: 'FAC-SG-44102',
    notes: 'Livraison complète reçue à l\'entrepôt Marrakech. Facture acquittée.',
  },
  {
    id: 'bc-2',
    numeroBC: 'BC-2026-0013',
    fournisseurId: 'fourn-3', // Sika Maroc
    dateCommande: '2026-10-01',
    dateLivraisonPrevue: '2026-10-04',
    dateReceptionReelle: '2026-10-04',
    agenceVille: 'Marrakech',
    lignes: [
      {
        id: 'lbc-3',
        articleId: 'art-6',
        designation: 'Cartouche Mastic Polyuréthane SikaTack Drive (300ml)',
        reference: 'COLLE-SIKA-DRIVE',
        quantite: 50,
        prixUnitaireAchatHT: 85,
        totalHT: 4250,
      },
      {
        id: 'lbc-4',
        articleId: 'art-7',
        designation: 'Primaire d\'adhérence noir Sika Primer-207 (100ml)',
        reference: 'PRIM-SIKA-207',
        quantite: 15,
        prixUnitaireAchatHT: 110,
        totalHT: 1650,
      },
    ],
    totalHT: 5900,
    tauxTva: 20,
    totalTVA: 1180,
    totalTTC: 7080,
    statutCommande: 'RECUE_CONFORME',
    statutPaiement: 'EN_ATTENTE_ECHEANCE',
    montantPaye: 0,
    modePaiement: 'CHEQUE',
    referencePaiement: 'CHQ N° 0459812',
    dateEcheancePaiement: '2026-10-31',
    numeroBLFournisseur: 'BL-SIKA-88712',
    notes: 'Chèque remis au livreur avec échéance fin de mois.',
  },
  {
    id: 'bc-3',
    numeroBC: 'BC-2026-0014',
    fournisseurId: 'fourn-2', // Pilkington
    dateCommande: '2026-10-05',
    dateLivraisonPrevue: '2026-10-09',
    agenceVille: 'El Jadida',
    lignes: [
      {
        id: 'lbc-5',
        articleId: 'art-3',
        designation: 'Pare-Brise Acoustique & Caméra ADAS - VW Golf VII / VIII',
        reference: 'PB-VW-GOLF7',
        codeEurocode: '8589AGS',
        quantite: 4,
        prixUnitaireAchatHT: 1400,
        totalHT: 5600,
      },
      {
        id: 'lbc-6',
        articleId: 'art-4',
        designation: 'Pare-Brise Athermique & Détecteur Pluie - Peugeot 208 II',
        reference: 'PB-PEU-208',
        codeEurocode: '6565AGS',
        quantite: 6,
        prixUnitaireAchatHT: 880,
        totalHT: 5280,
      },
    ],
    totalHT: 10880,
    tauxTva: 20,
    totalTVA: 2176,
    totalTTC: 13056,
    statutCommande: 'ENVOYEE',
    statutPaiement: 'ACOMPTE_VERSE',
    montantPaye: 4000,
    modePaiement: 'VIREMENT',
    referencePaiement: 'Acompte Vir BCP N° 8812',
    datePaiementEffectif: '2026-10-05',
    dateEcheancePaiement: '2026-10-25',
    notes: 'Commande urgente expédiée de Tanger vers l\'agence El Jadida. Solde à réception.',
  },
  {
    id: 'bc-4',
    numeroBC: 'BC-2026-0015',
    fournisseurId: 'fourn-1', // Saint-Gobain Sekurit
    dateCommande: '2026-10-07',
    dateLivraisonPrevue: '2026-10-12',
    agenceVille: 'Marrakech',
    lignes: [
      {
        id: 'lbc-7',
        articleId: 'art-5',
        designation: 'Lunette Arrière Dégivrante - Hyundai Tucson IV',
        reference: 'LA-HYU-TUC4',
        quantite: 3,
        prixUnitaireAchatHT: 1100,
        totalHT: 3300,
      },
    ],
    totalHT: 3300,
    tauxTva: 20,
    totalTVA: 660,
    totalTTC: 3960,
    statutCommande: 'BROUILLON',
    statutPaiement: 'NON_PAYE',
    montantPaye: 0,
    notes: 'Brouillon de commande en cours de finalisation selon besoins atelier.',
  },
];

export const INITIAL_DEVIS: DevisClient[] = [
  {
    id: 'dev-1',
    numeroDevis: 'DEV-2026-0012',
    dateDevis: '2026-10-06',
    dateValidite: '2026-11-06',
    agenceVille: 'Marrakech',
    clientNom: 'Samir Mansour',
    clientTelephone: '0661223344',
    clientCin: 'EE54210',
    clientVille: 'Marrakech',
    vehiculeMarque: 'Volkswagen',
    vehiculeModele: 'Golf 7',
    vehiculeAnnee: 2019,
    vehiculeImmatriculation: '45892|A|6',
    typeDemande: 'PARTICULIER_DIRECT',
    lignes: [
      {
        designation: 'Pare-Brise Teinté Vert avec Capteur de Pluie - VW Golf VII',
        codeEurocode: '8589AGSV',
        quantite: 1,
        prixUnitaireHT: 1250,
        tauxTva: 20,
        totalHT: 1250,
      },
      {
        designation: 'Kit colle polyuréthane & primaire d\'étanchéité constructeur',
        codeEurocode: 'SIKA-300ML',
        quantite: 1,
        prixUnitaireHT: 125,
        tauxTva: 20,
        totalHT: 125,
      },
      {
        designation: 'Main d\'œuvre pose et dépose pare-brise collé avec calibrage capteur',
        quantite: 1,
        prixUnitaireHT: 125,
        tauxTva: 20,
        totalHT: 125,
      },
    ],
    totalHT: 1500,
    totalTVA: 300,
    totalTTC: 1800,
    statut: 'ENVOYE',
    observations: 'Devis remis en main propre au client. Garantie étanchéité 1 an incluse.',
  },
  {
    id: 'dev-2',
    numeroDevis: 'DEV-2026-0013',
    dateDevis: '2026-10-07',
    dateValidite: '2026-11-07',
    agenceVille: 'El Jadida',
    clientNom: 'Nadia Cherkaoui',
    clientTelephone: '0665889900',
    clientCin: 'M789123',
    clientVille: 'El Jadida',
    vehiculeMarque: 'Hyundai',
    vehiculeModele: 'Tucson IV',
    vehiculeAnnee: 2022,
    vehiculeImmatriculation: '12450|B|26',
    typeDemande: 'ASSURANCE',
    compagnieAssurance: 'Sanlam Assurance',
    lignes: [
      {
        designation: 'Pare-Brise Acoustic & Caméra ADAS - Hyundai Tucson IV',
        codeEurocode: '4045ACCM',
        quantite: 1,
        prixUnitaireHT: 2083.33,
        tauxTva: 20,
        totalHT: 2083.33,
      },
      {
        designation: 'Kit colle polyuréthane haute performance SikaTack Drive',
        codeEurocode: 'SIKA-300ML',
        quantite: 1,
        prixUnitaireHT: 125,
        tauxTva: 20,
        totalHT: 125,
      },
      {
        designation: 'Main d\'œuvre pose et recollage embase caméra ADAS',
        quantite: 1,
        prixUnitaireHT: 125,
        tauxTva: 20,
        totalHT: 125,
      },
    ],
    totalHT: 2333.33,
    totalTVA: 466.67,
    totalTTC: 2800,
    statut: 'ACCEPTE',
    observations: 'Client en attente de validation de prise en charge Sanlam pour prise de rendez-vous atelier.',
  },
];


